<Project>
  <!-- SourceLink props must load before the corresponding .targets imports in project files. -->
  <Import Project="$(MSBuildThisFileDirectory)packages\Microsoft.Build.Tasks.Git.8.0.0\build\Microsoft.Build.Tasks.Git.props" Condition="Exists('$(MSBuildThisFileDirectory)packages\Microsoft.Build.Tasks.Git.8.0.0\build\Microsoft.Build.Tasks.Git.props')" />
  <Import Project="$(MSBuildThisFileDirectory)packages\Microsoft.SourceLink.Common.8.0.0\build\Microsoft.SourceLink.Common.props" Condition="Exists('$(MSBuildThisFileDirectory)packages\Microsoft.SourceLink.Common.8.0.0\build\Microsoft.SourceLink.Common.props')" />
  <Import Project="$(MSBuildThisFileDirectory)packages\Microsoft.SourceLink.GitHub.8.0.0\build\Microsoft.SourceLink.GitHub.props" Condition="Exists('$(MSBuildThisFileDirectory)packages\Microsoft.SourceLink.GitHub.8.0.0\build\Microsoft.SourceLink.GitHub.props')" />
</Project>
