//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminResource", typeof(AdminResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilenler ile Aksiyon.
        /// </summary>
        public static string ActionOptionsOfSelectedItems {
            get {
                return ResourceManager.GetString("ActionOptionsOfSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secilenleri silmeyi onayliyor musunuz?.
        /// </summary>
        public static string AdminDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("AdminDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici E-postası.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici E-posta Görünen Adı.
        /// </summary>
        public static string AdminEmailDisplayName {
            get {
                return ResourceManager.GetString("AdminEmailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici E-postasını SSL Etkinleştir .
        /// </summary>
        public static string AdminEmailEnableSsl {
            get {
                return ResourceManager.GetString("AdminEmailEnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici E-posta Host.
        /// </summary>
        public static string AdminEmailHost {
            get {
                return ResourceManager.GetString("AdminEmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici E-posta Parolası.
        /// </summary>
        public static string AdminEmailPassword {
            get {
                return ResourceManager.GetString("AdminEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici E-posta Port.
        /// </summary>
        public static string AdminEmailPort {
            get {
                return ResourceManager.GetString("AdminEmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici E-postası Varsayılan Kimlik Bilgilerini Kullan.
        /// </summary>
        public static string AdminEmailUseDefaultCredentials {
            get {
                return ResourceManager.GetString("AdminEmailUseDefaultCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Genel Ayarlar.
        /// </summary>
        public static string AdminGeneralSettings {
            get {
                return ResourceManager.GetString("AdminGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Sayfası.
        /// </summary>
        public static string AdminHome {
            get {
                return ResourceManager.GetString("AdminHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama.....
        /// </summary>
        public static string AdminMainSeachPlaceHolder {
            get {
                return ResourceManager.GetString("AdminMainSeachPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Ayarlari.
        /// </summary>
        public static string AdminSettings {
            get {
                return ResourceManager.GetString("AdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Kullanıcı Adı.
        /// </summary>
        public static string AdminUserName {
            get {
                return ResourceManager.GetString("AdminUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Ürünlerin Linki.
        /// </summary>
        public static string AllProductLinkText {
            get {
                return ResourceManager.GetString("AllProductLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Güvenlik Sorusunu Cevaplayın (İpucu: İki sayının toplamı).
        /// </summary>
        public static string AnswerSecurityQuestion {
            get {
                return ResourceManager.GetString("AnswerSecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misiniz?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geriye Dönün.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre değiştir.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket adresi.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adı.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifreyi onayla.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Onayla.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturma Tarihi.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni bir hesap oluştur.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şimdiki Şifre.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsayılan Resim Yüksekliği.
        /// </summary>
        public static string DefaultImageHeight {
            get {
                return ResourceManager.GetString("DefaultImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsayılan Resim Genişliği.
        /// </summary>
        public static string DefaultImageWidth {
            get {
                return ResourceManager.GetString("DefaultImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kayıtları gerçekten silmek istiyor musunuz? Bu işlem geri alınamaz..
        /// </summary>
        public static string DeletePopupDescription {
            get {
                return ResourceManager.GetString("DeletePopupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik açıklaması.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurtarmak için E-postanızı Girin.
        /// </summary>
        public static string EnterYourEmailToRecover {
            get {
                return ResourceManager.GetString("EnterYourEmailToRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel açıklama.
        /// </summary>
        public static string EntityDescriptionPage {
            get {
                return ResourceManager.GetString("EntityDescriptionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısa Özellikler.
        /// </summary>
        public static string EntityShortFields {
            get {
                return ResourceManager.GetString("EntityShortFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Ana Resim.
        /// </summary>
        public static string ExistingMainImageText {
            get {
                return ResourceManager.GetString("ExistingMainImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Dosyasına Aktar.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Link.
        /// </summary>
        public static string FacebookWebSiteLink {
            get {
                return ResourceManager.GetString("FacebookWebSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yükleme Sayfası.
        /// </summary>
        public static string FileUploadingPage {
            get {
                return ResourceManager.GetString("FileUploadingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altbilgi Açıklaması.
        /// </summary>
        public static string FooterDescription {
            get {
                return ResourceManager.GetString("FooterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altbilgi E-posta Listesi Açıklaması.
        /// </summary>
        public static string FooterEmailListDescription {
            get {
                return ResourceManager.GetString("FooterEmailListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikler kaydedilemedi. Tekrar deneyin ve sorun devam ederse sistem yöneticinize başvurun..
        /// </summary>
        public static string GeneralSaveErrorMessage {
            get {
                return ResourceManager.GetString("GeneralSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı için Yeni Şifre Oluştur.
        /// </summary>
        public static string GenerateNewPasswordforUser {
            get {
                return ResourceManager.GetString("GenerateNewPasswordforUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics Script.
        /// </summary>
        public static string GoogleAnalyticsTrackingScript {
            get {
                return ResourceManager.GetString("GoogleAnalyticsTrackingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GooglePlus Link.
        /// </summary>
        public static string GooglePlusWebSiteLink {
            get {
                return ResourceManager.GetString("GooglePlusWebSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Kayıtları Etkinleştir.
        /// </summary>
        public static string GridActiveSelectedButtonText {
            get {
                return ResourceManager.GetString("GridActiveSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Kayıtları Devre Dışı Bırak.
        /// </summary>
        public static string GridDeActiveSelectedButtonText {
            get {
                return ResourceManager.GetString("GridDeActiveSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Kayıtları Sil.
        /// </summary>
        public static string GridDeleteSelectedButtonText {
            get {
                return ResourceManager.GetString("GridDeleteSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string GridDeleteText {
            get {
                return ResourceManager.GetString("GridDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm seçimleri kaldır.
        /// </summary>
        public static string GridDeSelectAllButtonText {
            get {
                return ResourceManager.GetString("GridDeSelectAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string GridDetailText {
            get {
                return ResourceManager.GetString("GridDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string GridEditText {
            get {
                return ResourceManager.GetString("GridEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resimler.
        /// </summary>
        public static string GridImagesText {
            get {
                return ResourceManager.GetString("GridImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string GridMainPageImageText {
            get {
                return ResourceManager.GetString("GridMainPageImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Yok.
        /// </summary>
        public static string GridNoMainPageImageText {
            get {
                return ResourceManager.GetString("GridNoMainPageImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konumu Düzenle.
        /// </summary>
        public static string GridOrderingAllButtonText {
            get {
                return ResourceManager.GetString("GridOrderingAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalama.
        /// </summary>
        public static string GridPagingDropDownText {
            get {
                return ResourceManager.GetString("GridPagingDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Kayit.
        /// </summary>
        public static string GridResultRecordNumber {
            get {
                return ResourceManager.GetString("GridResultRecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama.
        /// </summary>
        public static string GridSearchButtonText {
            get {
                return ResourceManager.GetString("GridSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepsini seç.
        /// </summary>
        public static string GridSelectAllButtonText {
            get {
                return ResourceManager.GetString("GridSelectAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Boy.
        /// </summary>
        public static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resimler.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Durumu.
        /// </summary>
        public static string ImageState {
            get {
                return ResourceManager.GetString("ImageState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim En.
        /// </summary>
        public static string ImageWidth {
            get {
                return ResourceManager.GetString("ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Link.
        /// </summary>
        public static string InstagramWebSiteLink {
            get {
                return ResourceManager.GetString("InstagramWebSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Mi?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyada mı?.
        /// </summary>
        public static string IsCampaign {
            get {
                return ResourceManager.GetString("IsCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Fiyatı Etkin mi?.
        /// </summary>
        public static string IsProductPriceEnable {
            get {
                return ResourceManager.GetString("IsProductPriceEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsServices.
        /// </summary>
        public static string IsService {
            get {
                return ResourceManager.GetString("IsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValues.
        /// </summary>
        public static string IsValues {
            get {
                return ResourceManager.GetString("IsValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diller.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin Link.
        /// </summary>
        public static string LinkedinWebSiteLink {
            get {
                return ResourceManager.GetString("LinkedinWebSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link aktif mi?.
        /// </summary>
        public static string LinkIsActive {
            get {
                return ResourceManager.GetString("LinkIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta İçerik.
        /// </summary>
        public static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Zorunlu.
        /// </summary>
        public static string MailBodyPropertyRequiredErrorMessage {
            get {
                return ResourceManager.GetString("MailBodyPropertyRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Konusu.
        /// </summary>
        public static string MailSubject {
            get {
                return ResourceManager.GetString("MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta konusunun uygun hata mesajı olmalıdır.
        /// </summary>
        public static string MailSubjectPropertyErrorMessage {
            get {
                return ResourceManager.GetString("MailSubjectPropertyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Konusu Zorunlu.
        /// </summary>
        public static string MailSubjectPropertyRequiredErrorMessage {
            get {
                return ResourceManager.GetString("MailSubjectPropertyRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Şablonları.
        /// </summary>
        public static string MailTemplates {
            get {
                return ResourceManager.GetString("MailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa Resmi.
        /// </summary>
        public static string MainImageId {
            get {
                return ResourceManager.GetString("MainImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa Resimleri.
        /// </summary>
        public static string MainPageImages {
            get {
                return ResourceManager.GetString("MainPageImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Kategori Yap.
        /// </summary>
        public static string MakeItRootCategory {
            get {
                return ResourceManager.GetString("MakeItRootCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Link.
        /// </summary>
        public static string MenuLink {
            get {
                return ResourceManager.GetString("MenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Ana Kategori.
        /// </summary>
        public static string MenuParentId {
            get {
                return ResourceManager.GetString("MenuParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menuler.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebeveyn için aynı menüyü seçemezsiniz.
        /// </summary>
        public static string MenuSameSelectionErrorMessage {
            get {
                return ResourceManager.GetString("MenuSameSelectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Ağacı Adı.
        /// </summary>
        public static string MenuTreeName {
            get {
                return ResourceManager.GetString("MenuTreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO anahtar kelimeler.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim 500 karakterden uzun olamaz.
        /// </summary>
        public static string NamePropertyErrorMessage {
            get {
                return ResourceManager.GetString("NamePropertyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim Zorunlu.
        /// </summary>
        public static string NamePropertyRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NamePropertyRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısaltılmış isim.
        /// </summary>
        public static string NameShort {
            get {
                return ResourceManager.GetString("NameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Giriş.
        /// </summary>
        public static string NewRecordText {
            get {
                return ResourceManager.GetString("NewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni kullanıcı tanımla.
        /// </summary>
        public static string NewUserInsert {
            get {
                return ResourceManager.GetString("NewUserInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Ayarlar.
        /// </summary>
        public static string NormalSettings {
            get {
                return ResourceManager.GetString("NormalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonuç bulunamadı..
        /// </summary>
        public static string NoSearchResultsText {
            get {
                return ResourceManager.GetString("NoSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Teması.
        /// </summary>
        public static string PageTheme {
            get {
                return ResourceManager.GetString("PageTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre ve onay şifresi eşleşmiyor..
        /// </summary>
        public static string PasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel No.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Menü Kategorinizi Ağaçtan Seçin.
        /// </summary>
        public static string PleaseSelectYourMenuCategoryFromTree {
            get {
                return ResourceManager.GetString("PleaseSelectYourMenuCategoryFromTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ağaçtan Ürün Kategorinizi Seçiniz.
        /// </summary>
        public static string PleaseSelectYourProductCategoryFromTree {
            get {
                return ResourceManager.GetString("PleaseSelectYourProductCategoryFromTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası.
        /// </summary>
        public static string Privacypolicy {
            get {
                return ResourceManager.GetString("Privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategorileri.
        /// </summary>
        public static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategorisi.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategorisi İndirim Yüzdesi.
        /// </summary>
        public static string ProductCategoryDiscountPercantage {
            get {
                return ResourceManager.GetString("ProductCategoryDiscountPercantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori adı.
        /// </summary>
        public static string ProductCategoryId {
            get {
                return ResourceManager.GetString("ProductCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori ağacından kategori seçmelisiniz..
        /// </summary>
        public static string ProductCategoryIdErrorMessage {
            get {
                return ResourceManager.GetString("ProductCategoryIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategorisi.
        /// </summary>
        public static string ProductCategoryParentId {
            get {
                return ResourceManager.GetString("ProductCategoryParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategorisi Ağaç Adı.
        /// </summary>
        public static string ProductCategoryTreeName {
            get {
                return ResourceManager.GetString("ProductCategoryTreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Xml Şablonlar.
        /// </summary>
        public static string ProductDynamicTemplates {
            get {
                return ResourceManager.GetString("ProductDynamicTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Sayfası.
        /// </summary>
        public static string ProductPageTitle {
            get {
                return ResourceManager.GetString("ProductPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Aynı Seçim Hata Mesajı.
        /// </summary>
        public static string ProductSameSelectionErrorMessage {
            get {
                return ResourceManager.GetString("ProductSameSelectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ek Özellikleri.
        /// </summary>
        public static string ProductSpecs {
            get {
                return ResourceManager.GetString("ProductSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablonlarin Deger Listesi.
        /// </summary>
        public static string ProductSpecTemplateItemList {
            get {
                return ResourceManager.GetString("ProductSpecTemplateItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tazele.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt ol.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni hatırla?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu tarayıcıyı hatırla?.
        /// </summary>
        public static string RememberThisBrowser {
            get {
                return ResourceManager.GetString("RememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roler.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayit Et ve Kapat.
        /// </summary>
        public static string SaveButtonAndCloseText {
            get {
                return ResourceManager.GetString("SaveButtonAndCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Sonuçları.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama sonucu:.
        /// </summary>
        public static string SearchResultsText {
            get {
                return ResourceManager.GetString("SearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Kategori:.
        /// </summary>
        public static string SelectedCategory {
            get {
                return ResourceManager.GetString("SelectedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Atamalarını Seçin.
        /// </summary>
        public static string SelectRoleAssignments {
            get {
                return ResourceManager.GetString("SelectRoleAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Link Yolla.
        /// </summary>
        public static string SendEmailLink {
            get {
                return ResourceManager.GetString("SendEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayar Anahtar Kelimesi.
        /// </summary>
        public static string SettingKey {
            get {
                return ResourceManager.GetString("SettingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayar değeri.
        /// </summary>
        public static string SettingValue {
            get {
                return ResourceManager.GetString("SettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Dizini Meta Açıklama.
        /// </summary>
        public static string SiteIndexMetaDescription {
            get {
                return ResourceManager.GetString("SiteIndexMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Dizini Meta Anahtar Kelimeleri.
        /// </summary>
        public static string SiteIndexMetaKeywords {
            get {
                return ResourceManager.GetString("SiteIndexMetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Dizini Meta Başlığı.
        /// </summary>
        public static string SiteIndexMetaTitle {
            get {
                return ResourceManager.GetString("SiteIndexMetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Ayarları.
        /// </summary>
        public static string SmtpEmailSettings {
            get {
                return ResourceManager.GetString("SmtpEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabitler.
        /// </summary>
        public static string Static {
            get {
                return ResourceManager.GetString("Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloglar.
        /// </summary>
        public static string Stories {
            get {
                return ResourceManager.GetString("Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Kategorileri.
        /// </summary>
        public static string StoryCategories {
            get {
                return ResourceManager.GetString("StoryCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Kategorisi.
        /// </summary>
        public static string StoryCategory {
            get {
                return ResourceManager.GetString("StoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Kategorisi.
        /// </summary>
        public static string StoryCategoryId {
            get {
                return ResourceManager.GetString("StoryCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Blog Kategorisi seçin.
        /// </summary>
        public static string StoryCategoryIdErrorMessage {
            get {
                return ResourceManager.GetString("StoryCategoryIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Sayfasi.
        /// </summary>
        public static string StoryPageTitle {
            get {
                return ResourceManager.GetString("StoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aboneler.
        /// </summary>
        public static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Kategorileri.
        /// </summary>
        public static string TagCategories {
            get {
                return ResourceManager.GetString("TagCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Kategorisi.
        /// </summary>
        public static string TagCategory {
            get {
                return ResourceManager.GetString("TagCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Kategorisi.
        /// </summary>
        public static string TagCategoryId {
            get {
                return ResourceManager.GetString("TagCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Kategori İsim.
        /// </summary>
        public static string TagCategoryName {
            get {
                return ResourceManager.GetString("TagCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket İsim.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablon adı.
        /// </summary>
        public static string TemplateId {
            get {
                return ResourceManager.GetString("TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablonlar.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Şablon.
        /// </summary>
        public static string TemplateXml {
            get {
                return ResourceManager.GetString("TemplateXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şartlar ve Koşullar.
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Link.
        /// </summary>
        public static string TwitterWebSiteLink {
            get {
                return ResourceManager.GetString("TwitterWebSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme Tarihi.
        /// </summary>
        public static string UpdatedDate {
            get {
                return ResourceManager.GetString("UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Yönetimi.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Url.
        /// </summary>
        public static string VideoUrl {
            get {
                return ResourceManager.GetString("VideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sitesi Şirketi E-posta Adresi.
        /// </summary>
        public static string WebSiteCompanyEmailAddress {
            get {
                return ResourceManager.GetString("WebSiteCompanyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Telefon ve Adresi.
        /// </summary>
        public static string WebSiteCompanyPhoneAndLocation {
            get {
                return ResourceManager.GetString("WebSiteCompanyPhoneAndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Logo.
        /// </summary>
        public static string WebSiteLogo {
            get {
                return ResourceManager.GetString("WebSiteLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Link.
        /// </summary>
        public static string YoutubeWebSiteLink {
            get {
                return ResourceManager.GetString("YoutubeWebSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zopim.
        /// </summary>
        public static string Zopim {
            get {
                return ResourceManager.GetString("Zopim", resourceCulture);
            }
        }
    }
}
