//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminResource", typeof(AdminResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo Ücreti.
        /// </summary>
        public static string CargoPrice {
            get {
                return ResourceManager.GetString("CargoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikler kaydedilemedi. Tekrar deneyin ve sorun devam ederse sistem yöneticinize başvurun..
        /// </summary>
        public static string GeneralSaveErrorMessage {
            get {
                return ResourceManager.GetString("GeneralSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Kategori Yap.
        /// </summary>
        public static string MakeItRootCategory {
            get {
                return ResourceManager.GetString("MakeItRootCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori ağacından kategori seçmelisiniz..
        /// </summary>
        public static string ProductCategoryIdErrorMessage {
            get {
                return ResourceManager.GetString("ProductCategoryIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstek Geçerli Değil.
        /// </summary>
        public static string RequestIsNotValid {
            get {
                return ResourceManager.GetString("RequestIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayit Et ve Kapat.
        /// </summary>
        public static string SaveButtonAndCloseText {
            get {
                return ResourceManager.GetString("SaveButtonAndCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayit Et.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablon Seçin.
        /// </summary>
        public static string SelectTemplate {
            get {
                return ResourceManager.GetString("SelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminiz başarıyla gerçekleşmiştir..
        /// </summary>
        public static string SuccessfullySavedCompleted {
            get {
                return ResourceManager.GetString("SuccessfullySavedCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sitesi Şirketi E-posta Adresi uygun bir email adresi yaziniz. Zorunlu Alan..
        /// </summary>
        public static string WebSiteCompanyEmailAddressRequired {
            get {
                return ResourceManager.GetString("WebSiteCompanyEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş denemesi başarısız oldu..
        /// </summary>
        public static string WrongAccountLoginAttempt {
            get {
                return ResourceManager.GetString("WrongAccountLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış toplam, lütfen tekrar deneyin..
        /// </summary>
        public static string WrongSum {
            get {
                return ResourceManager.GetString("WrongSum", resourceCulture);
            }
        }
    }
}
