//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminResource", typeof(AdminResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Main Image.
        /// </summary>
        public static string ExistingMainImageText {
            get {
                return ResourceManager.GetString("ExistingMainImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Selected Records.
        /// </summary>
        public static string GridActiveSelectedButtonText {
            get {
                return ResourceManager.GetString("GridActiveSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActivate Selected Records.
        /// </summary>
        public static string GridDeActiveSelectedButtonText {
            get {
                return ResourceManager.GetString("GridDeActiveSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Records.
        /// </summary>
        public static string GridDeleteSelectedButtonText {
            get {
                return ResourceManager.GetString("GridDeleteSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GridDeleteText {
            get {
                return ResourceManager.GetString("GridDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string GridDeSelectAllButtonText {
            get {
                return ResourceManager.GetString("GridDeSelectAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string GridDetailText {
            get {
                return ResourceManager.GetString("GridDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GridEditText {
            get {
                return ResourceManager.GetString("GridEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string GridImagesText {
            get {
                return ResourceManager.GetString("GridImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string GridMainPageImageText {
            get {
                return ResourceManager.GetString("GridMainPageImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Image.
        /// </summary>
        public static string GridNoMainPageImageText {
            get {
                return ResourceManager.GetString("GridNoMainPageImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Position.
        /// </summary>
        public static string GridOrderingAllButtonText {
            get {
                return ResourceManager.GetString("GridOrderingAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging.
        /// </summary>
        public static string GridPagingDropDownText {
            get {
                return ResourceManager.GetString("GridPagingDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Number.
        /// </summary>
        public static string GridResultRecordNumber {
            get {
                return ResourceManager.GetString("GridResultRecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string GridSearchButtonText {
            get {
                return ResourceManager.GetString("GridSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string GridSelectAllButtonText {
            get {
                return ResourceManager.GetString("GridSelectAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageState.
        /// </summary>
        public static string ImageState {
            get {
                return ResourceManager.GetString("ImageState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPage.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        public static string NewRecordText {
            get {
                return ResourceManager.GetString("NewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
    }
}
