//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete eklendi!.
        /// </summary>
        public static string AddedToCart {
            get {
                return ResourceManager.GetString("AddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete ekle.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string AdminEdit {
            get {
                return ResourceManager.GetString("AdminEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Paneli Girişi.
        /// </summary>
        public static string AdminPanelLoginPage {
            get {
                return ResourceManager.GetString("AdminPanelLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepsi.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaten Üyeyim.
        /// </summary>
        public static string AlreadyMembered {
            get {
                return ResourceManager.GetString("AlreadyMembered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAMPANYALI ÜRÜNLER.
        /// </summary>
        public static string CampaignProducts {
            get {
                return ResourceManager.GetString("CampaignProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapmak için buraya tıklayın.
        /// </summary>
        public static string ClickHereToLogin {
            get {
                return ResourceManager.GetString("ClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string ContactUsAddress {
            get {
                return ResourceManager.GetString("ContactUsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guvenlik Sorusunu:.
        /// </summary>
        public static string ContactUsCaptcha {
            get {
                return ResourceManager.GetString("ContactUsCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Guvenlik Sorunu Cevaplayiniz..
        /// </summary>
        public static string ContactUsCaptchaErrorMessage {
            get {
                return ResourceManager.GetString("ContactUsCaptchaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirketiniz ismi.
        /// </summary>
        public static string ContactUsCompanyName {
            get {
                return ResourceManager.GetString("ContactUsCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string ContactUsEmail {
            get {
                return ResourceManager.GetString("ContactUsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen E-Postanizi girin.
        /// </summary>
        public static string ContactUsEmailErrorMessage {
            get {
                return ResourceManager.GetString("ContactUsEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajiniz.
        /// </summary>
        public static string ContactUsMessage {
            get {
                return ResourceManager.GetString("ContactUsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Mesajinizi Giriniz.
        /// </summary>
        public static string ContactUsMessageErrorMessage {
            get {
                return ResourceManager.GetString("ContactUsMessageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad / Soyad.
        /// </summary>
        public static string ContactUsName {
            get {
                return ResourceManager.GetString("ContactUsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ad / Soyadınızı Girin.
        /// </summary>
        public static string ContactUsNameErrorMessage {
            get {
                return ResourceManager.GetString("ContactUsNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string ContactUsPhone {
            get {
                return ResourceManager.GetString("ContactUsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Tel No Giriniz.
        /// </summary>
        public static string ContactUsPhoneErrorMessage {
            get {
                return ResourceManager.GetString("ContactUsPhoneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış Toplam, Lütfen tekrar deneyin..
        /// </summary>
        public static string ContactUsWrongSumForSecurityQuestion {
            get {
                return ResourceManager.GetString("ContactUsWrongSumForSecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabim.
        /// </summary>
        public static string CustomerAccount {
            get {
                return ResourceManager.GetString("CustomerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye ol.
        /// </summary>
        public static string CustomerRegister {
            get {
                return ResourceManager.GetString("CustomerRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-POSTA LİSTESİ.
        /// </summary>
        public static string EmailList {
            get {
                return ResourceManager.GetString("EmailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum Onayı.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi sıfırlamak için lütfen e-postanızı kontrol edin.
        /// </summary>
        public static string ForgotPasswordConfirmationText {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıkça Sorulan Sorular.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya.
        /// </summary>
        public static string IsCampaign {
            get {
                return ResourceManager.GetString("IsCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Gelen Yorumlar.
        /// </summary>
        public static string LatestReviews {
            get {
                return ResourceManager.GetString("LatestReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Yaz.
        /// </summary>
        public static string LeaveReview {
            get {
                return ResourceManager.GetString("LeaveReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum aç.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreni mi unuttun?.
        /// </summary>
        public static string LostYourPassword {
            get {
                return ResourceManager.GetString("LostYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorunlu Alan. Lütfen Boş bırakmayınız..
        /// </summary>
        public static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha fazla bilgi.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        public static string MyBasket {
            get {
                return ResourceManager.GetString("MyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni modellerimiz için tıklayınız.
        /// </summary>
        public static string NewModelsClick {
            get {
                return ResourceManager.GetString("NewModelsClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YENİ ÜRÜNLER.
        /// </summary>
        public static string NewProducts {
            get {
                return ResourceManager.GetString("NewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Sonucu Bulunamadi..
        /// </summary>
        public static string NOSearchResult {
            get {
                return ResourceManager.GetString("NOSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Kullanıcı Adı ve/veya Şifre.Lütfen bilgilerinizi kontrol ediniz..
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Özeti.
        /// </summary>
        public static string OrderFinalReview {
            get {
                return ResourceManager.GetString("OrderFinalReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş numarası.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişi Tamamla.
        /// </summary>
        public static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişi Tamamla.
        /// </summary>
        public static string ProceedToCheckout {
            get {
                return ResourceManager.GetString("ProceedToCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün No :.
        /// </summary>
        public static string ProductCodeNo {
            get {
                return ResourceManager.GetString("ProductCodeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Bilgisi.
        /// </summary>
        public static string ProductInformation {
            get {
                return ResourceManager.GetString("ProductInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} için Ürün Arama Sonucu.
        /// </summary>
        public static string ProductSearchPageTitle {
            get {
                return ResourceManager.GetString("ProductSearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Bilgisi.
        /// </summary>
        public static string ProductsInfo {
            get {
                return ResourceManager.GetString("ProductsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section class=&quot;uvFaq typeset&quot;&gt;
        ///                        &lt;p style=&quot;font-size:x-large&quot;&gt;
        ///                            Herhangi bir konu hakkinda soru veya istek için ürünü satan satıcıyla doğrudan iletişime geçin.
        ///                        &lt;/p&gt;
        ///                        &lt;h3&gt;Bir konu hakkında soru&lt;/h3&gt;
        ///                        &lt;p&gt;
        ///                            &lt;font class=&quot;Apple-style-span&quot; color=&quot;#2e2f33&quot;&gt;
        ///                                &lt;span class=&quot;Apple-style-span&quot;
        ///                                      styl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QuestionAboutItemForCustomer {
            get {
                return ResourceManager.GetString("QuestionAboutItemForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devami....
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedenler.
        /// </summary>
        public static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurtarmak.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre kurtarma.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 class=&quot;h3 mb-4&quot;&gt;Parolanızı mı unuttunuz?&lt;/h2&gt;
        ///                &lt;p&gt;Şifrenizi üç kolay adımda değiştirin.  Bu, yeni şifrenizi güvende tutmanıza yardımcı olur.&lt;/p&gt;
        ///                &lt;ol class=&quot;list-unstyled&quot;&gt;
        ///                    &lt;li&gt;&lt;span class=&quot;font-weight-semibold text-primary mr-2&quot;&gt;1.&lt;/span&gt;E-posta adresinizi aşağıya girin.&lt;/li&gt;
        ///                    &lt;li&gt;&lt;span class=&quot;font-weight-semibold text-primary mr-2&quot;&gt;2.&lt;/span&gt;Size geçici bir kod göndereceğiz.&lt;/li&gt;
        ///                    &lt;li&gt;&lt;span class=&quot;font-weight-s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RecoverPasswordText {
            get {
                return ResourceManager.GetString("RecoverPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt ol.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili Bloglar.
        /// </summary>
        public static string RelatedBlogsForProducts {
            get {
                return ResourceManager.GetString("RelatedBlogsForProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili Ürünler.
        /// </summary>
        public static string RelatedProductsForBlog {
            get {
                return ResourceManager.GetString("RelatedProductsForBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi yenile.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola sıfırlamayı onayla.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz sıfırlandı. Giriş yapmak için lütfen aşağıdaki bağlantıyı tıklayın..
        /// </summary>
        public static string ResetPasswordConfirmationText {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişini gözden geçir.
        /// </summary>
        public static string ReviewYourOrder {
            get {
                return ResourceManager.GetString("ReviewYourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Yapmak için lütfen birşeyler yazınız.
        /// </summary>
        public static string SearchErrorMessage {
            get {
                return ResourceManager.GetString("SearchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string SearchProductButtonText {
            get {
                return ResourceManager.GetString("SearchProductButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler arasında arama yapın.
        /// </summary>
        public static string SearchProductTextBoxPlaceHolder {
            get {
                return ResourceManager.GetString("SearchProductTextBoxPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir arama terimi girin 2.
        /// </summary>
        public static string SearchRequiredErrorMessage {
            get {
                return ResourceManager.GetString("SearchRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} için Arama Sonucu.
        /// </summary>
        public static string SearchResultText {
            get {
                return ResourceManager.GetString("SearchResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir metin girin 2.
        /// </summary>
        public static string SearchValidText {
            get {
                return ResourceManager.GetString("SearchValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden seçin.
        /// </summary>
        public static string SelectReason {
            get {
                return ResourceManager.GetString("SelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir neden seçin..
        /// </summary>
        public static string SelectReasonsLabel {
            get {
                return ResourceManager.GetString("SelectReasonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta gönder.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü paylaş.
        /// </summary>
        public static string ShareProduct {
            get {
                return ResourceManager.GetString("ShareProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VİTRİN ÜRÜNLERİ.
        /// </summary>
        public static string ShowcaseProducts {
            get {
                return ResourceManager.GetString("ShowcaseProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzer Urunler.
        /// </summary>
        public static string SimilairProducts {
            get {
                return ResourceManager.GetString("SimilairProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal medya.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellikler.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberdar olun.
        /// </summary>
        public static string StayInformed {
            get {
                return ResourceManager.GetString("StayInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone ol.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKLE.
        /// </summary>
        public static string SubscriberButtonText {
            get {
                return ResourceManager.GetString("SubscriberButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erken indirim teklifleri, güncellemeler ve yeni ürün bilgileri almak için bültenimize abone olun..
        /// </summary>
        public static string SubscriptionInfo {
            get {
                return ResourceManager.GetString("SubscriptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminiz başarıyla gerçekleşmiştir..
        /// </summary>
        public static string SuccessfullySavedCompleted {
            get {
                return ResourceManager.GetString("SuccessfullySavedCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Resimler.
        /// </summary>
        public static string TechnicalPictures {
            get {
                return ResourceManager.GetString("TechnicalPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şartlar ve Koşullar.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonelik için teşekkürler.
        /// </summary>
        public static string ThanksForSubscription {
            get {
                return ResourceManager.GetString("ThanksForSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temasa geçtiğiniz için teşekkür ederiz! Bizimle iletişime geçtiğiniz için teşekkür ederiz. Mümkün olan en kısa zamanda yanıt vermeye çalışıyoruz, bu nedenle Müşteri Hizmetleri çalışma arkadaşlarımızdan biri birkaç saat içinde size geri dönecek. Günün geri kalanı güzel geçsin!.
        /// </summary>
        public static string ThankYouContactUsForm {
            get {
                return ResourceManager.GetString("ThankYouContactUsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimle iletişime geçtiğiniz için teşekkürler.
        /// </summary>
        public static string ThankYouForContactingUs {
            get {
                return ResourceManager.GetString("ThankYouForContactingUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ürün sepetinize eklendi..
        /// </summary>
        public static string ThisItemAddedYourCart {
            get {
                return ResourceManager.GetString("ThisItemAddedYourCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Ürün Hakkında Bilgi İstiyorum.
        /// </summary>
        public static string WantMoreInfoAboutProduct {
            get {
                return ResourceManager.GetString("WantMoreInfoAboutProduct", resourceCulture);
            }
        }
    }
}
